matrixfact: matrixfact.cpp
	g++ matrixfact.cpp -g -I ../include -L ../bin -lHalide -lpthread -ldl -o matrixfact -std=c++11

matrixfact_iter: matrixfact_iter.cpp
	g++ matrixfact_iter.cpp -g -I ../include -L ../bin -lHalide -lpthread -ldl -o matrixfact_iter -std=c++11
